var s = function (sketch) {
  var x = 100;
  var y = 100;
  let portion1;
  let border_load;
  let border_create;
  let border_create2;
  let border_create3;
  let border_create4;
  let border_create5;
  let planet1;
  let planet2;
  let planet3;
  let planet4;
  let planet5;
  let planet6;
  let zodiacwheel;
  let zodiac1;
  let zodiac2;
  let zodiac3;
  let zodiac4;
  let zodiac5;
  let zodiac6;
  let zodiac7;
  let zodiac8;
  let zodiac9;
  let zodiac10;
  let zodiac11;
  let zodiac12;
  let myth;
  let lovers;
  let tarot2;
  let tarot3;
  let tarot4;
  let godfont;
  sketch.preload = function () {
    portion1 = sketch.loadImage("images/p2.jpg");
     lovers = sketch.loadImage("images/lovers.png");
    tarot2 = sketch.loadImage("images/world.png");
    tarot3 = sketch.loadImage("images/death.png");
    tarot4 = sketch.loadImage("images/highP.png");
  godfont = sketch.loadFont('Goddess of Fortune.ttf');
    zodiacwheel = sketch.loadImage("images/zodiacc.png");
    border_load = sketch.loadImage("images/Sliver_stars.gif");
    border_create = sketch.createImg("images/Sliver_stars.gif");
    border_create2 = sketch.createImg("images/Sliver_stars.gif");
    border_create3 = sketch.createImg("images/Sliver_stars.gif");
    border_create4 = sketch.createImg("images/Sliver_stars.gif");
    border_create5 = sketch.createImg("images/Sliver_stars.gif");
    planet1 = sketch.createImg("images/sun.gif");
    planet2 = sketch.createImg("images/uranus.gif");
    planet3 = sketch.createImg("images/mars.gif");
    planet4 = sketch.createImg("images/jupiter.gif");
    planet5 = sketch.createImg("images/saturn.gif");
    planet6 = sketch.createImg("images/moon.gif");
    zodiac1 = sketch.createImg("images/aqua.gif");
    zodiac2 = sketch.createImg("images/aries.gif");
    zodiac3 = sketch.createImg("images/cancer.gif");
    zodiac4 = sketch.createImg("images/capricorn.gif");
    zodiac5 = sketch.createImg("images/gemini.gif");
    zodiac6 = sketch.createImg("images/leo.gif");
    zodiac7 = sketch.createImg("images/libra.gif");
    zodiac8 = sketch.createImg("images/pisces.gif");
    zodiac9 = sketch.createImg("images/currsag.gif");
    zodiac10 = sketch.createImg("images/scorpio.gif");
    zodiac11 = sketch.createImg("images/taurus.gif");
    zodiac12 = sketch.createImg("images/virgo.gif");
    myth = sketch.createImg("images/mythologygold.gif");
    
    
  };
  sketch.setup = function () {
   sketch.createCanvas(1450,750);
  };

  sketch.draw = function () {
    sketch.background(portion1);
        sketch.fill(0);
    sketch.textSize(38);
    sketch.textFont(godfont);
    sketch.image(zodiacwheel, 580, 250, 300, 300);
    sketch.text('Aquarius is known for being progressive, idealistic, intelligent, and highly creative', 0, 600);
    sketch.text('Virgos are known for being practical, sensible, and loyal', 0, 650);
    sketch.text('Aries are spontaneous and courageous, they have a sense of adventure ', 0, 550);
    sketch.text('Taureans are known to be intelligent, dependable, hardworking, dedicated, and stubborn', 0, 500);
    sketch.text('Sagittarius values independence and the ability to do what they want, when they want', 0, 450);
    sketch.text('Cancers have a reputation for being hyper emotional, temperamental, and spiteful.', 0, 400);
    sketch.text('Leos are honest in their individual connections, super high ego. ', 0, 350);
    sketch.text('Libras are known for being charming, beautiful, and well-balanced.', 0, 300);
    sketch.text('Cancers are ambitious, organized, goal-oriented,and they dont mind the hustle.', 0, 250);
    sketch.text('Gemini is constantly juggling a variety of passions, hobbies, careers, and friend groups', 0, 200);
    sketch.text('Pisces people are known for being emotionally sensitive, gracious, and emotionally aware.', 0, 150);
    
    sketch.image(lovers, 0, 150, 80, 180);
    sketch.image(tarot2, 0, 480, 80, 180);
    sketch.image(tarot3, 1350, 150, 80, 180);
    sketch.image(tarot4, 1350, 480, 80, 180);
   border_create.position(0, 1500,'fixed');
    border_create2.position(310, 1500,'fixed');
    border_create3.position(615, 1500,'fixed');
    border_create4.position(920, 1500,'fixed');
    border_create5.position(1165, 1500,'fixed');
    planet1.position(0, 1525,'fixed');
    planet2.position(5, 1900,'fixed');
    planet3.position(5, 2175,'fixed');
    planet4.position(1350, 1525,'fixed');
    planet5.position(1327, 1875,'fixed');
    planet6.position(1350, 2175,'fixed');
    zodiac1.position(150, 1525,'fixed');
    zodiac2.position(360, 1525,'fixed');
    zodiac3.position(500, 1525,'fixed');
    zodiac4.position(700, 1525,'fixed');
    zodiac5.position(900, 1525,'fixed');
    zodiac6.position(1100, 1525,'fixed');
    zodiac7.position(150, 2175,'fixed');
    zodiac8.position(360, 2175,'fixed');
    zodiac9.position(500, 2175,'fixed');
    zodiac10.position(700, 2175,'fixed');
    zodiac11.position(900, 2175,'fixed');
    zodiac12.position(1100, 2175,'fixed');
    myth.position(x, 1600);
    x = x + 1;
if( x*2 > sketch.width ) 
  x = 0;
  };
  
};

var myp5 = new p5(s, "p5sketch");

var s2 = function (sketch) {
  var x = 100;
  var y = 100;
  let portion2;
  let gif1;
  let gif2;
  let gif2_1;
  let gif2_2;
  let gif2_3;
  let gif2_4;
  let gif2_5;
  let gif2_6;
  let gif2_7;
  let gif2_8;
  let gif2_9;
  let gif2_10;
  let gif2_11;
  let gif3;
  let gif31;
  let gif32;
  let gif33;
  let gif34;
  let gif35;
  let gif36;
  let gif37;
  let gif38;
  let gif39;
  let gif40;
  let gif41;
  let gif42;
  let gif43;
  let gif44;
  let gif45;
  let gif46;
  let gif47;
  let gif48;
  let gif49;
  let gif50;
  let gif51;
  let gif52;
  let gif53;
  let gif4;
  let gif5;
  let gif6;
  let gif7;
  let gif8;
  let gif9;
  let gif10;
  let gif11;
  let gif12;
  let gif13;
  let gif14;
  let gif15;
  let gif16;
  let gif17;
  let gif18;
  let gif19;
  let gif20;
  let gif21;
  let gif22;
  let gif23;
  let gif24;
  let gif25;
  let gif26;
let gif27;
  let gif28;
  let gif29;
  let gif30;
  let gif_31;
  let gif_32;
  let gif_33;
  let gif_34;
  let gif_35;
  let gif_36;
  let gif_37;
  
  let font1;
  sketch.preload = function () {
    portion2 = sketch.loadImage("images/portion2.JPG");
    font1 = sketch.loadFont('LOVELY HEART.ttf');
    gif26 = sketch.loadImage("sec1/hellokitty.png");
   gif27 = sketch.loadImage("sec1/diamond.png");
    gif1 = sketch.createImg("sec1/Girly1.gif");
    gif2 = sketch.createImg("sec1/PinKhEaRtBeCc.gif");
gif2_1 = sketch.createImg("sec1/PinKhEaRtBeCc.gif");
gif2_2 = sketch.createImg("sec1/PinKhEaRtBeCc.gif");
gif2_3 = sketch.createImg("sec1/PinKhEaRtBeCc.gif");
gif2_4 = sketch.createImg("sec1/PinKhEaRtBeCc.gif");
gif2_5 = sketch.createImg("sec1/PinKhEaRtBeCc.gif"); 
gif2_6 = sketch.createImg("sec1/PinKhEaRtBeCc.gif"); 
  gif2_7 = sketch.createImg("sec1/PinKhEaRtBeCc.gif"); 
     gif2_8 = sketch.createImg("sec1/PinKhEaRtBeCc.gif"); 
     gif2_9 = sketch.createImg("sec1/PinKhEaRtBeCc.gif");
    gif2_10 = sketch.createImg("sec1/PinKhEaRtBeCc.gif");
     gif2_11 = sketch.createImg("sec1/PinKhEaRtBeCc.gif");
    gif3 = sketch.createImg("sec1/ampinksparkles.gif");
    gif31 = sketch.createImg("sec1/ampinksparkles.gif");
    gif32 = sketch.createImg("sec1/ampinksparkles.gif");
    gif33 = sketch.createImg("sec1/ampinksparkles.gif");
    gif34 = sketch.createImg("sec1/ampinksparkles.gif");
    gif35 = sketch.createImg("sec1/ampinksparkles.gif");
    gif36 = sketch.createImg("sec1/ampinksparkles.gif");
    gif37 = sketch.createImg("sec1/ampinksparkles.gif");
    gif38 = sketch.createImg("sec1/ampinksparkles.gif");
    gif39 = sketch.createImg("sec1/ampinksparkles.gif");
    gif40 = sketch.createImg("sec1/ampinksparkles.gif");
    gif41 = sketch.createImg("sec1/ampinksparkles.gif");
    gif42 = sketch.createImg("sec1/ampinksparkles.gif");
    gif43 = sketch.createImg("sec1/ampinksparkles.gif");
    gif44 = sketch.createImg("sec1/ampinksparkles.gif");
    gif45 = sketch.createImg("sec1/ampinksparkles.gif");
    gif46 = sketch.createImg("sec1/ampinksparkles.gif");
    gif47 = sketch.createImg("sec1/ampinksparkles.gif");
    gif48 = sketch.createImg("sec1/ampinksparkles.gif");
    gif49 = sketch.createImg("sec1/ampinksparkles.gif");
    gif50 = sketch.createImg("sec1/ampinksparkles.gif");
    gif51 = sketch.createImg("sec1/ampinksparkles.gif");
    gif52 = sketch.createImg("sec1/ampinksparkles.gif");
    gif53 = sketch.createImg("sec1/ampinksparkles.gif");
    gif4 = sketch.createImg("sec1/babygirl.gif");
    gif5 = sketch.createImg("sec1/backpink.gif");
    gif6 = sketch.createImg("sec1/bratz.gif");
    gif7 = sketch.createImg("sec1/bunny.gif");
    gif8 = sketch.createImg("sec1/butterflypink.gif");
    gif9 = sketch.createImg("sec1/butterflypink.gif");
    gif10 = sketch.createImg("sec1/butterflypink.gif");
     gif11 = sketch.createImg("sec1/butterflypink.gif");
    gif12 = sketch.createImg("sec1/butterflypink2.gif");
    gif13 = sketch.createImg("sec1/envelopepink.gif");
    gif14 = sketch.createImg("sec1/girly.gif");
    gif15 = sketch.createImg("sec1/home.gif");
    gif16 = sketch.createImg("sec1/home_pink.gif");
    gif17 = sketch.createImg("sec1/i_love_shopping.gif");
    gif18 = sketch.createImg("sec1/pink-fairy.gif");
    gif19 = sketch.createImg("sec1/pink_file.gif");
    gif20 = sketch.createImg("sec1/pinkkiss.gif");
    gif21 = sketch.createImg("sec1/pinkrose.gif");
    gif22 = sketch.createImg("sec1/pinkxoxo.gif");
    gif23 = sketch.createImg("sec1/pnkglitterav.gif");
    gif24 = sketch.createImg("sec1/welcome.gif");
    gif25 = sketch.createImg("sec1/yerrr.gif");
    gif28 = sketch.createImg("sec1/pinkkiss.gif");
    gif29 = sketch.createImg("sec1/anipink_figure.gif");
    gif30 = sketch.createImg("sec1/371.gif");
    gif_31 = sketch.createImg("sec1/daisybuttonpink.gif");
   gif_32 = sketch.createImg("sec1/gif3.gif");
    gif_33 = sketch.createImg("sec1/hartspink.gif");
    gif_34 = sketch.createImg("sec1/lightpinkbubbles.gif");
    gif_35 = sketch.createImg("sec1/pinkaddictblinkie.gif");
  };
  sketch.setup = function () {
   sketch.createCanvas(1450,750);
  };

  sketch.draw = function () {
    sketch.background(portion2);
    sketch.image(gif26, 955, 80, 100, 100);
    sketch.image(gif27, 700, 20, 150, 150);
    gif1.position(80, 100,'fixed');
    gif2.position(0, 0,'fixed');
    gif2_1.position(250, 0,'fixed');
    gif2_2.position(500, 0,'fixed');
    gif2_3.position(750, 0,'fixed');
    gif2_4.position(1000, 0,'fixed');
    gif2_5.position(1200, 0,'fixed');
    gif2_6.position(0, 730,'fixed');
gif2_7.position(250, 730,'fixed');
    
    gif2_8.position(500, 730,'fixed');
    gif2_9.position(750, 730,'fixed');
    gif2_10.position(1000, 730,'fixed');
    gif2_11.position(1200, 730,'fixed');
    gif3.position(0, 660,'fixed');
    gif31.position(0, 600,'fixed');
    gif32.position(0, 540,'fixed');
    gif33.position(0, 480,'fixed');
    gif34.position(0, 420,'fixed');
    gif35.position(0, 360,'fixed');
    gif36.position(0, 300,'fixed');
    gif37.position(0, 240,'fixed');
    gif38.position(0, 180,'fixed');
    gif39.position(0, 120,'fixed');
    gif40.position(0, 60,'fixed');
    gif41.position(0, 10,'fixed');
    
    gif42.position(1375, 660,'fixed');
    gif43.position(1375, 600,'fixed');
    gif44.position(1375, 540,'fixed');
    gif45.position(1375, 480,'fixed');
    gif46.position(1375, 420,'fixed');
    gif47.position(1375, 360,'fixed');
    gif48.position(1375, 300,'fixed');
    gif49.position(1375, 240,'fixed');
    gif50.position(1375, 180,'fixed');
    gif51.position(1375, 120,'fixed');
    gif52.position(1375, 60,'fixed');
    gif53.position(1375, 10,'fixed');
    gif4.position(80, 595,'fixed');
    gif5.position(1260, 685,'fixed');
    gif6.position(1215, 335,'fixed');
    gif7.position(1215, 100,'fixed');
    gif8.position(70, 30,'fixed');
    gif9.position(800, 400,'fixed');
    gif10.position(1115, 125,'fixed');
    gif11.position(350, 300,'fixed');
    gif12.position(550, 35,'fixed');
    gif13.position(510, 670,'fixed');
     gif14.position(1000, 600,'fixed');
    gif15.position(1200, 20,'fixed');
    gif16.position(900, 20,'fixed');
    gif17.position(1000, 20,'fixed');
    gif19.position(1135, 30,'fixed');
    gif18.position(70, 230,'fixed');
    gif20.position(500, 500,'fixed');
    gif21.position(1000, 355,'fixed');
    gif22.position(500, 300,'fixed');
    gif23.position(500, 90,'fixed');
    gif24.position(200, 20,'fixed');
    gif25.position(830, 150,'fixed');
    gif28.position(250, 150,'fixed');
    gif29.position(250, 300,'fixed');
    sketch.fill(243,99,186);
    sketch.textSize(20);
    sketch.textFont(font1);
    sketch.text('About me!', 80, 400);
    sketch.text('Age : 21 years old', 80, 435);
    sketch.text('Zodiac sign : Aquarius', 80, 455);
    sketch.text('Relationship status: doesnt take me serious', 80, 475);
    sketch.text('Last login: 08/21/2015', 80, 495);
    sketch.text('Mood: Sleepy asf', 80, 515);
    sketch.text('I am currently trying to make it ', 80, 540);
        sketch.text('Just the beginning ', 450, 255);
    gif30.position(850, 600,'fixed');
    gif_31.position(800, 480,'fixed');
    gif_32.position(750, 300,'fixed');
    gif_33.position(680, 600,'fixed');
    gif_34.position(940, 300,'fixed');
    gif_35.position(550, 450,'fixed');
  };
};

var myp5_2 = new p5(s2, "p5sketch");
var s3 = function (sketch) {
  var x = 100;
  var y = 100;
  var x1 = 300;
  var y1 = 100;
  let portion3;
  let windowpop;
  let puprplewin;
  let gif1_load;
  let gif1_create;
  let gif2_load;
  let gif2_create;
  let gif3_load;
  let gif3_create;
  let gif4_create;
  let gif5_create;
  let gif6_create;
  let gif7_create;
  let gif8_load;
  let gif8_create;
  let gif9_load;
  let gif9_create;
    let gif10_load;
  let gif10_create;
let gif11_create;
  let gif12_create;
  let gif13_create;
  let gif14_create;
   let gif15_create;
   let gif16_create;
  let compu_font;
  
  let retrowindows;
  let colors;
  let immensepopups;
  sketch.preload = function () {
    compu_font = sketch.loadFont('Old computer St.ttf');
    portion3 = sketch.loadImage("images/portion3.jpg");
    windowpop = sketch.loadImage("images/mini.PNG");
    puprplewin = sketch.loadImage("images/popup.PNG");
    colors = sketch.loadImage("images/colors.PNG");
    immensepopups = sketch.loadImage("images/BAM.png")
    gif1_load = sketch.loadImage("images/intro_09.gif");
    gif1_create = sketch.createImg("images/intro_09.gif");
    retrowindows = sketch.loadImage("images/purplewindwos.png");
    gif2_load = sketch.loadImage("images/geek.gif");
    gif2_create = sketch.createImg("images/geek.gif");
    gif3_load = sketch.loadImage("images/purplehearts.gif");
    gif3_create = sketch.createImg("images/purplehearts.gif");
    //gif4_load = sketch.loadImage("images/purplehearts.gif");
    gif4_create = sketch.createImg("images/purplehearts.gif");
    gif5_create = sketch.createImg("images/purplehearts.gif");
    gif6_create = sketch.createImg("images/purplehearts.gif");
    gif7_create = sketch.createImg("images/purplehearts.gif");
    gif8_create = sketch.createImg("images/links.gif");
    gif9_create = sketch.createImg("images/emailbest.gif");
gif10_create = sketch.createImg("images/pchead.gif");
    gif11_create = sketch.createImg("images/computer.gif");
     gif12_create = sketch.createImg("images/intro_09.gif");
     gif13_create = sketch.createImg("images/intro_09.gif");
    gif14_create = sketch.createImg("images/mouseclick.gif");
    gif15_create = sketch.createImg("images/laptops.gif");
    gif16_create = sketch.createImg("images/google.gif");

  };
  sketch.setup = function () {
     sketch.createCanvas(1450,750);
  };

  sketch.draw = function () {
    sketch.background(portion3);
    sketch.image(windowpop, -168, 300, 530, 530);
    sketch.image(puprplewin, -98, -140, 400, 400);
    sketch.image(immensepopups, 200,150, 400, 400);
    sketch.image(colors, 200,150, 200, 200);
    sketch.fill(255);
    sketch.textSize(45);
    sketch.textFont(compu_font);
    sketch.text('Welcome to Jessicas Page', 450, 650);
    sketch.image(retrowindows, 1235, 200, 200, 200);
    
    gif1_create.position(30, 1000,'fixed');
    gif2_create.position(700, 1100,'fixed');
    gif3_create.position(0, 1480,'fixed');
    gif4_create.position(300, 1480,'fixed');
    gif5_create.position(600, 1480,'fixed');
    gif6_create.position(900, 1480,'fixed');
    gif7_create.position(1100, 1480,'fixed');
    gif9_create.position(900, 1250,'fixed');
    gif10_create.position(1265, 1190,'fixed');
    gif11_create.position(300, 765,'fixed');
    gif12_create.position(90, 890,'fixed');
    gif13_create.position(-39, 1110,'fixed');
     gif14_create.position(250, 1345,'fixed');
    gif15_create.position(700, 900,'fixed');
    gif16_create.position(650, 770,'fixed');
  gif8_create.position(x, 1440);
    x = x + 1;

if( x > sketch.width ) 
  x = 0; 
}
  
  

};

var myp5_3 = new p5(s3, "p5sketch");
